build_task:
  matrix:
    - name: FreeBSD 13
      freebsd_instance:
        image: freebsd-13-4-release-amd64
    - name: FreeBSD 14
      freebsd_instance:
        image: freebsd-14-1-release-amd64-ufs
  setup_script:
    sudo pkg install -y lua54 cmake igor expect
  configure_script:
    - mkdir build
    - cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
  build_script:
    - make -C build
  test_script:
    - sudo chmod 0755 $HOME
    - sudo make -C build check
